name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        config: [1-minimal, 2-matlab, 3-jupyter, 5-gui]
        include:
        - config: 1-minimal
          command: uname -a
          platform: linux/amd64,linux/arm64
          push: always
        - config: 2-matlab
          command: matlab -h || true # matlab -h returns 1 causing action to fail
          platform: linux/amd64,linux/arm64
          push: always
        - config: 3-jupyter
          command: radian --version
          platform: linux/amd64      # RStudio Server does not support ARM architecture
          push: always
        - config: 5-gui
          command: vncserver --version
          platform: linux/amd64,linux/arm64
          push: never

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Run ${{ matrix.config }} Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/${{ matrix.config }}/devcontainer.json
          imageName: ghcr.io/dddlab/container-computing/${{ matrix.config }}
          cacheFrom: ghcr.io/dddlab/container-computing/${{ matrix.config }}
          platform: ${{ matrix.platform }}
          push: ${{ matrix.push }}
          runCmd: ${{ matrix.command }}
      