name: 'build example' 
on: workflow_dispatch # manually run, see build-image.yml for automation on push/pull request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Run Minimal Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/1-minimal/devcontainer.json
          imageName: ghcr.io/392781/1-minimal
          cacheFrom: ghcr.io/392781/1-minimal
          push: never
          runCmd: uname -a
      
      - name: Build/Run Alternate Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/2-alternate/devcontainer.json
          imageName: ghcr.io/392781/2-alternate
          cacheFrom: ghcr.io/392781/2-alternate
          push: never
          runCmd: g++ --version

      - name: Build/Run RStudio Container
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/3-rstudio/devcontainer.json
          imageName: ghcr.io/392781/3-rstudio
          cacheFrom: ghcr.io/392781/3-rstudio
          push: never
          runCmd: rstudio-server version

      - name: Build/Run Customized Container
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/4-customized/devcontainer.json
          imageName: ghcr.io/392781/4-customized
          cacheFrom: ghcr.io/392781/4-customized
          push: always
          runCmd: radian --version

      - name: Build/Run GUI Container
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/6-gui/devcontainer.json
          imageName: ghcr.io/392781/6-gui
          cacheFrom: ghcr.io/392781/6-gui
          push: never
          runCmd: vncserver --version
